const C=['Alimentação','Transporte','Moradia','Educação','Saúde','Lazer','Assinaturas','Trabalho','Investimentos','Cartão','Transferência','Outros'];const $=i=>document.getElementById(i),BRL=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),M=(d=new Date())=>d.toISOString().slice(0,7);let flow,cat,defer;const db=JSON.parse(localStorage.getItem('rfv8'))||{wallets:[],tx:[],cards:[],invest:[],goals:[],budgets:{},cats:C,theme:'dark',privacy:false};
function save(){localStorage.setItem('rfv8',JSON.stringify(db));render()}function cur(){return db.tx.filter(x=>x.month===M())}function totals(a=cur()){return a.reduce((o,x)=>{x.type==='income'?o.i+=x.amount:o.e+=x.amount;return o},{i:0,e:0})}function net(){return db.wallets.reduce((a,w)=>a+w.balance,0)+db.invest.reduce((a,i)=>a+i.amount,0)}function debt(){return cur().filter(x=>x.cardId).reduce((a,x)=>a+x.amount,0)}function invT(){return db.invest.reduce((a,i)=>a+i.amount,0)}function byCat(){let m={};cur().filter(x=>x.type==='expense').forEach(x=>m[x.cat]=(m[x.cat]||0)+x.amount);return m}
function render(){document.body.classList.toggle('light',db.theme==='light');document.body.classList.toggle('privacy',db.privacy);date.textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'});selects();dash();wallets();txs();cards();budgets();invest();goals();reports()}
function selects(){let cats=db.cats.map(c=>`<option>${c}</option>`).join('');category.innerHTML=cats;budgetCat.innerHTML=cats;filterCat.innerHTML='<option value="all">Todas categorias</option>'+cats;let ws=db.wallets.map(w=>`<option value="${w.id}">${w.name}</option>`).join('');walletSel.innerHTML='<option value="">Sem carteira</option>'+ws;fromWallet.innerHTML=ws;toWallet.innerHTML=ws;parcelCard.innerHTML=db.cards.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}
function dash(){let t=totals(),bal=t.i-t.e,sav=t.i?Math.round(bal/t.i*100):0,sc=Math.max(0,Math.min(100,50+sav-(debt()>t.i*.5?20:0)));netEl=$('net');netEl.innerHTML=`<span class="money">${BRL(net())}</span>`;income.innerHTML=`<span class="money">${BRL(t.i)}</span>`;expense.innerHTML=`<span class="money">${BRL(t.e)}</span>`;cardDebt.innerHTML=`<span class="money">${BRL(debt())}</span>`;invTotal.innerHTML=`<span class="money">${BRL(invT())}</span>`;saveRate.textContent=sav+'%';proj.innerHTML=`<span class="money">${BRL(net()+bal*12)}</span>`;score.textContent=sc;let al=alerts(t,bal);insight.textContent=al[0];alerts.innerHTML=al.map(a=>`<div class="ai">${a}</div>`).join('');dueSoonRender();charts()}
function alerts(t,bal){let a=[];if(!db.wallets.length)a.push('💼 Crie uma carteira para controlar bancos, Pix e dinheiro.');if(!t.i)a.push('💡 Cadastre sua renda para melhorar as análises.');if(bal<0)a.push('⚠️ Saldo mensal negativo.');if(debt()>t.i*.5&&t.i>0)a.push('💳 Fatura do cartão acima de 50% da renda.');let b=byCat();Object.entries(db.budgets).forEach(([c,l])=>{if((b[c]||0)>l)a.push(`🚨 Orçamento de ${c} ultrapassado.`)});if(db.goals.length&&bal>0)a.push('🎯 Direcione parte do saldo para suas metas.');return a.length?a:['✅ Finanças equilibradas neste mês.']}
function dueSoonRender(){let now=new Date(),soon=cur().filter(x=>x.dueDate).filter(x=>{let d=new Date(x.dueDate);return d>=now&&(d-now)/86400000<=10});dueSoon.innerHTML=soon.map(x=>`<div class="row"><b>${x.desc}</b><span>${x.dueDate} • ${BRL(x.amount)}</span></div>`).join('')||'<p>Sem vencimentos próximos.</p>'}
function charts(){if(!window.Chart)return;let t=totals();if(flow)flow.destroy();flow=new Chart(flowChart,{type:'bar',data:{labels:['Receitas','Despesas','Cartões'],datasets:[{data:[t.i,t.e,debt()]}]}});let b=byCat();if(cat)cat.destroy();cat=new Chart(catChart,{type:'doughnut',data:{labels:Object.keys(b),datasets:[{data:Object.values(b)}]}});let max=Math.max(1,...Object.values(b));bars.innerHTML=Object.entries(b).map(([c,v])=>`<div><small>${c} ${BRL(v)}</small><div class="bar"><span style="width:${v/max*100}%"></span></div></div>`).join('')}
function wallets(){walletList.innerHTML=db.wallets.map(w=>`<div class="row"><div><b>${w.name}</b><div class="tag">${w.type}</div></div><b class="money">${BRL(w.balance)}</b><button class="delete" onclick="delWallet('${w.id}')">Excluir</button></div>`).join('')||'<p>Nenhuma carteira.</p>'}
function txs(){let q=(search.value||'').toLowerCase(),ft=filter.value,fc=filterCat.value;let list=cur().filter(x=>(ft==='all'||x.type===ft)&&(fc==='all'||x.cat===fc)&&x.desc.toLowerCase().includes(q));txList.innerHTML=list.map(x=>`<div class="row"><div><b>${x.desc}</b><div class="tag">${x.cat} • ${x.walletName||'sem carteira'} ${x.inst?'• parcela '+x.inst:''}</div></div><b class="${x.type} money">${x.type==='income'?'+':'-'} ${BRL(x.amount)}</b><button class="delete" onclick="delTx('${x.id}')">Excluir</button></div>`).join('')||'<p>Nenhuma movimentação.</p>'}
function cards(){cardList.innerHTML=db.cards.map(c=>{let used=db.tx.filter(x=>x.cardId===c.id&&x.month===M()).reduce((a,x)=>a+x.amount,0);return `<div class="row"><div><b>${c.name}</b><div class="tag">Usado ${BRL(used)} de ${BRL(c.limit)} • vence dia ${c.due}</div></div><button class="delete" onclick="delCard('${c.id}')">Excluir</button></div>`}).join('')||'<p>Nenhum cartão.</p>'}
function budgets(){let b=byCat();budgetList.innerHTML=Object.entries(db.budgets).map(([c,l])=>{let u=b[c]||0,p=Math.min(100,Math.round(u/l*100));return `<div class="row"><div style="width:100%"><b>${c}</b><p>${BRL(u)} de ${BRL(l)} • ${p}%</p><div class="bar"><span style="width:${p}%"></span></div></div><button class="delete" onclick="delBudget('${c}')">Excluir</button></div>`}).join('')||'<p>Nenhum orçamento.</p>'}
function invest(){let total=invT(),future=db.invest.reduce((a,i)=>a+i.amount*Math.pow(1+i.rate/100,12),0);invProjection.textContent=db.invest.length?`Projeção 12 meses: ${BRL(future)} (hoje ${BRL(total)})`:'Cadastre investimentos.';invList.innerHTML=db.invest.map(i=>`<div class="row"><div><b>${i.name}</b><div class="tag">${i.type} • ${i.rate}% ao mês</div></div><b class="money">${BRL(i.amount)}</b><button class="delete" onclick="delInvest('${i.id}')">Excluir</button></div>`).join('')||'<p>Nenhum investimento.</p>'}
function goals(){goalList.innerHTML=db.goals.map(g=>{let p=Math.min(100,Math.round(g.saved/g.target*100));return `<div class="goal"><div style="width:100%"><b>${g.name}</b><p>${BRL(g.saved)} de ${BRL(g.target)} • ${p}%</p><div class="bar"><span style="width:${p}%"></span></div></div><button class="delete" onclick="delGoal('${g.id}')">Excluir</button></div>`}).join('')||'<p>Nenhuma meta.</p>'}
function reports(){let m={};db.tx.forEach(x=>{m[x.month]??={i:0,e:0};x.type==='income'?m[x.month].i+=x.amount:m[x.month].e+=x.amount});summary.innerHTML=Object.entries(m).sort().reverse().map(([k,v])=>`<div class="row"><b>${k}</b><span class="money">Receitas ${BRL(v.i)} • Despesas ${BRL(v.e)} • Saldo ${BRL(v.i-v.e)}</span></div>`).join('')||'<p>Sem relatórios.</p>'}
window.delWallet=id=>{db.wallets=db.wallets.filter(x=>x.id!==id);save()};window.delTx=id=>{db.tx=db.tx.filter(x=>x.id!==id);save()};window.delCard=id=>{db.cards=db.cards.filter(x=>x.id!==id);save()};window.delInvest=id=>{db.invest=db.invest.filter(x=>x.id!==id);save()};window.delGoal=id=>{db.goals=db.goals.filter(x=>x.id!==id);save()};window.delBudget=c=>{delete db.budgets[c];save()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav,.page').forEach(x=>x.classList.remove('on'));b.classList.add('on');$(b.dataset.p).classList.add('on');title.textContent=b.textContent})
walletForm.onsubmit=e=>{e.preventDefault();db.wallets.push({id:crypto.randomUUID(),name:walletName.value,type:walletType.value,balance:Number(walletBalance.value||0)});walletForm.reset();save()}
transferForm.onsubmit=e=>{e.preventDefault();let f=db.wallets.find(x=>x.id===fromWallet.value),t=db.wallets.find(x=>x.id===toWallet.value),v=Number(transferAmount.value);if(f&&t&&f.id!==t.id){f.balance-=v;t.balance+=v;db.tx.push({id:crypto.randomUUID(),desc:`Transferência ${f.name} → ${t.name}`,amount:v,type:'expense',cat:'Transferência',date:new Date().toISOString(),month:M()});save()}transferForm.reset()}
txForm.onsubmit=e=>{e.preventDefault();let w=db.wallets.find(x=>x.id===walletSel.value),v=Number(amount.value);db.tx.push({id:crypto.randomUUID(),desc:desc.value,amount:v,type:type.value,cat:category.value,walletId:w?.id,walletName:w?.name,dueDate:dueDate.value,recurring:recurring.checked,date:new Date().toISOString(),month:M()});if(w)w.balance+=type.value==='income'?v:-v;txForm.reset();save()}
cardForm.onsubmit=e=>{e.preventDefault();db.cards.push({id:crypto.randomUUID(),name:cardName.value,limit:Number(cardLimit.value||0),due:cardDue.value});cardForm.reset();save()}
parcelForm.onsubmit=e=>{e.preventDefault();let total=Number(parcelAmount.value),n=Number(parcelCount.value),c=db.cards.find(x=>x.id===parcelCard.value),part=total/n;for(let i=0;i<n;i++){let d=new Date();d.setMonth(d.getMonth()+i);db.tx.push({id:crypto.randomUUID(),desc:parcelDesc.value,amount:part,type:'expense',cat:'Cartão',cardId:c?.id,cardName:c?.name,inst:`${i+1}/${n}`,date:new Date().toISOString(),month:M(d)})}parcelForm.reset();save()}
budgetForm.onsubmit=e=>{e.preventDefault();db.budgets[budgetCat.value]=Number(budgetLimit.value);budgetForm.reset();save()}
invForm.onsubmit=e=>{e.preventDefault();db.invest.push({id:crypto.randomUUID(),name:invName.value,type:invType.value,amount:Number(invAmount.value||0),rate:Number(invRate.value||0)});invForm.reset();save()}
goalForm.onsubmit=e=>{e.preventDefault();db.goals.push({id:crypto.randomUUID(),name:goalName.value,target:Number(goalTarget.value||0),saved:Number(goalSaved.value||0)});goalForm.reset();save()}
simGoal.onclick=()=>{let g=db.goals[0],v=Number(monthlySave.value);goalSim.textContent=g&&v>0?`Guardando ${BRL(v)}/mês, alcança "${g.name}" em ${Math.ceil((g.target-g.saved)/v)} mês(es).`:'Crie uma meta e informe valor.'}
plan.onclick=()=>{let t=totals(),bal=t.i-t.e;planText.innerHTML=`<div class="ai"><b>Plano inteligente do mês</b><p>1. Priorize despesas essenciais.<br>2. Reserve ${BRL(Math.max(0,bal*.3))} para metas/investimentos.<br>3. Revise cartões: ${BRL(debt())}.<br>4. Busque economia acima de 20%.</p></div>`}
theme.onclick=()=>{db.theme=db.theme==='dark'?'light':'dark';save()};privacy.onclick=()=>{db.privacy=!db.privacy;save()};search.oninput=txs;filter.onchange=txs;filterCat.onchange=txs;sample.onclick=()=>{db.wallets.push({id:crypto.randomUUID(),name:'Nubank',type:'Banco',balance:1200});db.tx.push({id:crypto.randomUUID(),desc:'Salário',amount:1800,type:'income',cat:'Trabalho',date:new Date().toISOString(),month:M()},{id:crypto.randomUUID(),desc:'Mercado',amount:430,type:'expense',cat:'Alimentação',date:new Date().toISOString(),month:M()});save()}
function down(n,c,t){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type:t}));a.download=n;a.click()}csv.onclick=()=>{let r=['Data,Mes,Tipo,Categoria,Descricao,Valor,Carteira,Cartao'];db.tx.forEach(x=>r.push(`${x.date},${x.month},${x.type},${x.cat},"${x.desc}",${x.amount},${x.walletName||''},${x.cardName||''}`));down('ramalho-finance-v8.csv',r.join('\n'),'text/csv')};backup.onclick=()=>down('ramalho-finance-v8-backup.json',JSON.stringify(db,null,2),'application/json');restore.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{Object.assign(db,JSON.parse(r.result));save()};r.readAsText(f)};printBtn.onclick=()=>print();clear.onclick=()=>{if(confirm('Apagar tudo?')){localStorage.removeItem('rfv8');location.reload()}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();defer=e});install.onclick=()=>defer?defer.prompt():alert('Use o menu do navegador e escolha Instalar aplicativo.')
function bg(){let c=$('bg'),x=c.getContext('2d'),w,h,p;function rz(){w=c.width=innerWidth;h=c.height=innerHeight;p=Array.from({length:Math.min(100,Math.floor(w*h/14000))},()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.6,vy:(Math.random()-.5)*.6}))}function loop(){x.clearRect(0,0,w,h);x.fillStyle='rgba(34,211,238,.7)';p.forEach(a=>{a.x+=a.vx;a.y+=a.vy;if(a.x<0||a.x>w)a.vx*=-1;if(a.y<0||a.y>h)a.vy*=-1;x.beginPath();x.arc(a.x,a.y,1.4,0,7);x.fill()});x.strokeStyle='rgba(34,211,238,.11)';for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++){let dx=p[i].x-p[j].x,dy=p[i].y-p[j].y;if(dx*dx+dy*dy<9000){x.beginPath();x.moveTo(p[i].x,p[i].y);x.lineTo(p[j].x,p[j].y);x.stroke()}}requestAnimationFrame(loop)}rz();addEventListener('resize',rz);loop()}bg();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js')
